### ISSUE TITLE
`ValueError: error formatting value` when inserting JSON array (`List[dict]`) into `json[]` column

### ISSUE THREAD

**Issue by SamuelMarks** [altaurog/pgcopy#34]
```
Traceback (most recent call last):
  […]
    mgr.copy(data_iter)
  File "pgcopy/pgcopy/copy.py", line 295, in copy
    self.writestream(data, datastream)
  File "pgcopy/pgcopy/copy.py", line 323, in writestream
    f, d = formatter(val)
  File "pgcopy/pgcopy/copy.py", line 136, in <lambda>
    return lambda v: ('i', (-1,)) if v is None else formatter(v)
  File "pgcopy/pgcopy/copy.py", line 214, in f
    errors.raise_from(ValueError, message, exc)
  File "pgcopy/pgcopy/errors/py3.py", line 9, in raise_from
    raise exccls(message) from exc
ValueError: error formatting value [{'thekey': None, 'text': 'stuff'}] for column json_arr_col
```

```sql
CREATE TABLE my_table (
    json_arr_col json[],
    json_col json,
    vchar20_col VARCHAR(20),
    id integer generated by default as identity primary key
);
```

**Comment by altaurog** [comment]
I see you need to [pass it json strings](https://github.com/altaurog/pgcopy/blob/master/tests/test_datatypes.py#L173-L182), not objects.  We could potentially implement some magic here, but I am not sure if it is a good idea:

```python
from pgcopy import CopyManager
import psycopg2

cols = ('json_arr_col', 'json_col', 'vchar20_col')
records = [
    (
        ['{"thekey": null, "text": "stuff"}'],
        '{"a": 2}',
        'quick fox',
    ),
]

conn = psycopg2.connect(database='test_db')
mgr = CopyManager(conn, 'my_table', cols)
mgr.copy(records)

conn.commit()
```

**Comment by SamuelMarks** [comment]
@altaurog Thanks that solved the issue, now trying to coalesce the correct `NULL` type:
```python
from datetime import datetime
from functools import partial
from json import dumps

import numpy as np
from pgcopy import CopyManager


def parse_col(col):
    """
    Parse column into something `COPY FROM` can deal with

    :param col: Column
    :type col: ```Any```

    :return: A variant of the input that `COPY FROM` can deal with
    :rtype: ```Any```
    """
    if isinstance(col, np.ndarray):
        return parse_col(col.tolist()) if col.size > 0 else "NULL"
    elif isinstance(col, bool):
        return int(col)
    elif isinstance(col, bytes):
        try:
            return parse_col(col.decode("utf8"))
        except UnicodeError:
            print("unable to decode: {!r} ;".format(col))
            raise
    elif isinstance(col, (complex, int)):
        return col
    elif isinstance(col, float):
        return int(col) if col.is_integer() else col
    elif col in (None, "{}", "[]") or not col:
        return "NULL"
    elif isinstance(col, str):
        return {"True": 1, "False": 0}.get(col, col)
    elif isinstance(col, (list, tuple, set, frozenset)):
        return list(map("'{}'".format, map(parse_col, col)))
    elif isinstance(col, dict):
        return dumps(col, separators=(",", ":"))
    elif isinstance(col, datetime):
        return col.isoformat()
    else:
        raise NotImplementedError(type(col))


def psql_insert_copy(table, conn, keys, data_iter):
    """
    Execute SQL statement inserting data

    Parameters
    ----------
    table : pandas.io.sql.SQLTable
    conn : sqlalchemy.engine.Engine or sqlalchemy.engine.Connection
    keys : list of str
        Column names
    data_iter : Iterable that iterates the values to be inserted
    """

    with conn.connection.cursor() as cur:
        table_name = psycopg2.sql.Identifier(
            *(table.schema, table.name) if table.schema else (table.name,)
        ).as_string(cur)

    mgr = CopyManager(
        conn.connection, table.name, keys[1:] if keys and keys[0] == "index" else keys
    )
    mgr.copy(map(lambda line: map(parse_col, line), data_iter))
    conn.connection.commit()
```

ValueError: error formatting value NULL for column thiscol0

Where `thiscol0` has type:
```
timestamp with time zone
```

**Comment by SamuelMarks** [comment]
@altaurog Thanks that solved the issue:
```python
from datetime import datetime
from functools import partial
from json import dumps

import numpy as np
from pgcopy import CopyManager


def parse_col(col):
    """
    Parse column into something `COPY FROM` can deal with

    :param col: Column
    :type col: ```Any```

    :return: A variant of the input that `COPY FROM` can deal with
    :rtype: ```Any```
    """
    if isinstance(col, np.ndarray):
        return parse_col(col.tolist()) if col.size > 0 else None
    elif isinstance(col, bool):
        return int(col)
    elif isinstance(col, bytes):
        try:
            return parse_col(col.decode("utf8"))
        except UnicodeError:
            print("unable to decode: {!r} ;".format(col))
            raise
    elif isinstance(col, (complex, int)):
        return col
    elif isinstance(col, float):
        return int(col) if col.is_integer() else col
    elif col in (None, "{}", "[]") or not col:
        return None
    elif isinstance(col, str):
        return {"True": 1, "False": 0}.get(col, col)
    elif isinstance(col, (list, tuple, set, frozenset)):
        return list(map("'{}'".format, map(parse_col, col)))
    elif isinstance(col, dict):
        return dumps(col, separators=(",", ":"))
    elif isinstance(col, datetime):
        return col
    else:
        raise NotImplementedError(type(col))


def psql_insert_copy(table, conn, keys, data_iter):
    """
    Execute SQL statement inserting data

    Parameters
    ----------
    table : pandas.io.sql.SQLTable
    conn : sqlalchemy.engine.Engine or sqlalchemy.engine.Connection
    keys : list of str
        Column names
    data_iter : Iterable that iterates the values to be inserted
    """

    with conn.connection.cursor() as cur:
        table_name = psycopg2.sql.Identifier(
            *(table.schema, table.name) if table.schema else (table.name,)
        ).as_string(cur)

    mgr = CopyManager(
        conn.connection, table.name, keys[1:] if keys and keys[0] == "index" else keys
    )
    mgr.copy(map(lambda line: map(parse_col, line), data_iter))
    conn.connection.commit()
```

Now debugging the actual insert with real-world data:
```
File line 101, in psql_insert_copy
    mgr.copy(map(lambda line: map(parse_col, line), data_iter))
  File "pgcopy/pgcopy/copy.py", line 297, in copy
    self.copystream(datastream)
  File "pgcopy/pgcopy/copy.py", line 348, in copystream
    raise e
  File "pgcopy/pgcopy/copy.py", line 344, in copystream
    cursor.copy_expert(cmd, datastream)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
DETAIL:  Token "'" is invalid.
CONTEXT:  JSON data, line 1: '...
COPY MyTableName, line 1, column json_arr_col
```

**Comment by altaurog** [comment]
perhaps you should remove the single-quotes here?
```python
    elif isinstance(col, (list, tuple, set, frozenset)):
        return list(map("'{}'".format, map(parse_col, col)))
```
If you are inserting to `json`, this should also be just `dumps(col)`.  For `json[]` it should be `list(map(dumps, col))`.

**Comment by SamuelMarks** [comment]
Perfect, thanks
